version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./static:/sirius_cpi/static
      - ./templates:/sirius_cpi/templates
    environment:
      - PYTHONUNBUFFERED=1